### ISSUE TITLE
Full access to `.config`

### ISSUE THREAD

**Issue by dluciv** [mdouchement/docker-zoom-us#11]
Zoom stores its config right inside `$XDG_CONFIG_HOME`. Right now, [it is reflected in wrapper script](https://github.com/mdouchement/docker-zoom-us/blob/f305e0cca4238640eccfc3b561ea017a5d559816/scripts/zoom-us-wrapper#L55).

As there were many claims on privacy ragarding Zoom, it might be better to have an option to lock it just within some subdirectory. It will not pick up real config file, but it will also lose access to the whole `.config`, which, I guess, is desired by many users.

**Comment by mdouchement** [comment]
It should be possible. We need to check what files is created by Zoom in the `.config` and add some constraint on the mount argument.
I don't have the time to test but Zoom may use a sub-directory like `.config/zoom`.

**Comment by KevOrr** [comment]
It doesn't appear to use a subdirectory in `~/.config` but rather `~/.config/zoomus.conf`

**Comment by dluciv** [comment]
`Unknown Organization`... Nice... I increasingly believe Zoom is a malware %)))

**Comment by mdouchement** [comment]
Maybe `~/.config/zoomus.conf` is the only file that need to be persistent?
Here something that may be interesting: https://github.com/detrout/apparmor-det/blob/master/opt.zoom.ZoomLauncher#L110-L142

**Comment by mdouchement** [comment]
Use `export ZOOM_HOME=${HOME}/zoomus` to restrict Zoom access.
