### ISSUE TITLE
Single Sign-On needs non-embedded browser, which is unaccessible

### ISSUE THREAD

**Issue by konteal** [mdouchement/docker-zoom-us#12]
There is an issue with zoom that it hangs on login attempts via SSO on “Connecting …” when using the embedded browser with `embeddedBrowserForSSOLogin=true`, see the issues at [aur/zoom](https://aur.archlinux.org/packages/zoom/#pinned-735665) or [github/NixOS/nixpkgs](
https://github.com/NixOS/nixpkgs/issues/73532). A workaround is to simply *not* use the embedded browser, having `embeddedBrowserForSSOLogin=false`.

However, this docker image cannot launch a browser, see #10. So Single Sign-On simply doesn’t work. I believe to fix this, one would either need to integrate a browser or to make zoom communicate with the host browser from within the docker image …

**Comment by mdouchement** [comment]
Can you please retry?

**Comment by konteal** [comment]
> Can you please retry?

Seems to work. In the meantime, I integrated netsurf with which Single-Sign-On also did work. I now switched to your build again. Thanks!
