### ISSUE TITLE
Mount user (host) directory to store saved meetings

### ISSUE THREAD

**Issue by peleion** [mdouchement/docker-zoom-us#18]
When a meeting is saved the media files are transcoded and stored in the container but are not accessible to the user or persist on the host. 

I've added to prepare_docker_volume_parameters()

`VOLUMES+=" --volume=${DOWNLOAD_DIR}:/home/${ZOOM_US_USER}/Documents/Zoom"`

and now the files are persistent and accessible by the user. It probably needs some logic to test whether the dir exists on the host as I'm not sure if ~/Downloads is widely used but I think it is, at least on Debian/Ubuntu and Fedora. I could throw together a PR with documentation if needed.

**Comment by mdouchement** [comment]
I've made #19 to address this issue.
I'm currently encountering some errors with QT and my VM so I can't test it right now.

**Comment by mdouchement** [comment]
Fixed in #19
