### ISSUE TITLE
Get screen sharing to work

### ISSUE THREAD

**Issue by konteal** [mdouchement/docker-zoom-us#20]
Momentarily, screen sharing doesn’t work. It shows a black screen for other participants. This is probably a good default setting – I imagine it fails because Zoom cannot access what’s on your screen. It still would be nice to get it to work since it’s an essential feature for Zoom.

**Comment by konteal** [comment]
As a workaround, one can load the `v4l2loopack` kernel module (which is a out-of-tree module), which creates a dummy video device, and feed the output for an X display via `ffmpeg` to it, see the questtons [superuser/411897](https://superuser.com/questions/411897/using-desktop-as-fake-webcam-on-linux) and [unix.stackexchange/528400](https://unix.stackexchange.com/questions/528400/how-can-i-stream-my-desktop-screen-to-dev-video1-as-a-fake-webcam-on-linux).

However, Zoom does lowers image quality for video streams and frame rate for sharing screens on bad connections. The latter being the smarter option for sharing screens, this workaround is of limited value.

**Comment by mdouchement** [comment]
Yes I used v4l2loopback + ffmpeg as fake webcam to dev on this project lately, it works but it's not the best experience.

I don't how zoom and other software do the screen sharing.

**Comment by KevOrr** [comment]
Odd, you would think if it has access to the X server, then it would just work. It works just fine for me in Gnome (wayland). Maybe check your `xhost` settings? Mine is set to `SI:localuser:$USER`, where `$USER` is my username, so you could try `xhost +SI:localuser:"$USER"`.

If allowing just your user doesn't work, then you could try `xhost +local:`

**Comment by konteal** [comment]
> Odd, you would think if it has access to the X server, then it would just work. It works just fine for me in Gnome (wayland). Maybe check your `xhost` settings? Mine is set to `SI:localuser:$USER`, where `$USER` is my username, so you could try `xhost +SI:localuser:"$USER"`.
> 
> If allowing just your user doesn't work, then you could try `xhost +local:`

Huh. You’re right. `xhost +SI:localuser:"$USER"` did it for me.

**Comment by chemmi** [comment]
> Note: I had an issue with the screen not refreshing for the participants until the window shared has lost focus. This was “fixed” by deactivating the “Limit frame rate” option in Zoom.

I ran into the same side-issue, that my shared window was not refreshed until that very window lost focus. Deactivating the frame rate did not fix this (it was deactivated by default in my setting).

However, activating "Share selected app window only" magically fixed this issue in my case.

**Comment by faxm0dem** [comment]
I have the same issue, and the `xhost` workaround doesn't work for me

**Comment by gzqx** [comment]
Got same issue and `xhost` don't work as well

**Comment by faxm0dem** [comment]
I ended up using v4l2 as a workarount.
Maybe this  can help others so posting it here for debian:
```
sudo apt install v4l2loopback-dkms v4l2loopback-utils ffmpeg
sudo modprobe v4l2loopback devices=1 exclusive_caps=1
# adjust the correct video device and video size
ffmpeg -video_size 1920x1080 -f x11grab -framerate 24 -i :0 -vcodec rawvideo -pix_fmt yuv420p -f v4l2 /dev/video2
```

Then I just switch camera during the conference. Works with jitsi too of course
