### ISSUE TITLE
[linux] error: tandard_init_linux.go:211: exec user process caused "exec format error" when i try to run the wrapper script

### ISSUE THREAD

**Issue by Suyashtnt** [mdouchement/docker-zoom-us#21]

**Comment by mdouchement** [comment]
Is the wrapper runned from your host?

**Comment by Suyashtnt** [comment]
> Is the wrapper runned from your host?

Uh, I'm new to docker and it's on a 32bit version of ZorinOS 15(base or Ubuntu 18.04 LTS I think). That's all I know
