### ISSUE TITLE
Issues signing in / connecting to servers

### ISSUE THREAD

**Issue by WilliamBehrens** [mdouchement/docker-zoom-us#32]
It appears that it's having trouble signing me in, I'm able to sign in the browser but the container is having trouble. I all it tells me in terms of errors is just a timeout error after it fails to connect.

**Comment by mdouchement** [comment]
I can singin without issue. Did you blocked some zoomus domains?

Here you can find how to get some logs https://github.com/mdouchement/docker-zoom-us#troubleshooting

**Comment by peaceful-james** [comment]
@WilliamBehrens Did you try setting the zoomus config as per https://github.com/mdouchement/docker-zoom-us#web-browser--sso ?
