### ISSUE TITLE
The timezone in the container is not correct

### ISSUE THREAD

**Issue by kapilch21** [mdouchement/docker-zoom-us#40]
The wrapper uses the wrong method of reading the timezone of the host computer. Therefore the container gets the wrong timezone. It should use the long timezone instead of short one. Eg. instead of 'PDT', use America/Los_Angeles

I didn't seem to have the permissions to create a branch or a pull request to this repository, so please consider this one liner patch instead. Thanks...

```
diff --git a/scripts/zoom-us-wrapper b/scripts/zoom-us-wrapper
index aadc86e..8642b45 100755
--- a/scripts/zoom-us-wrapper
+++ b/scripts/zoom-us-wrapper
@@ -49,7 +49,7 @@ prepare_docker_env_parameters() {
   ENV_VARS+=" --env=USER_GID=${USER_GID}"
   ENV_VARS+=" --env=DISPLAY=unix$DISPLAY"
   ENV_VARS+=" --env=XAUTHORITY=${XAUTH}"
-  ENV_VARS+=" --env=TZ=$(date +%Z)"
+  ENV_VARS+=" --env=TZ=$(timedatectl show --value -p Timezone)"
 }
 
 prepare_docker_volume_parameters() {
```

**Comment by mdouchement** [comment]
Hello, thanks for the patch.
To open a PR you need to fork this repository: https://github.com/firstcontributions/first-contributions

**Comment by CholoTook** [comment]
Thanks both, please close the issue :-)

**Comment by CholoTook** [comment]
Thanks
