### ISSUE TITLE
Audio not working. Please help!!!

### ISSUE THREAD

**Issue by HexagonWin** [mdouchement/docker-zoom-us#44]
Hello!
I'm in Debian GNU/Linux 11 bullseye
I removed systemd and installed sysvinit
And I'm using CDE (Common Desktop Environment) with dtlogin.
Pulse audio works with this (https://sourceforge.net/p/cdesktopenv/wiki/Sound-Video%20and%20dtlogin/) workaround.
However, when I install and launch zoom with this, whole audio stuffs aren't working.
In zoom, the audio device itself are not being detected. Both mic and speaker.
In zoom there's login function, so I clicked in it to launch firefox inside zoom container, and in there firefox I tested audio, and it doesn't work there too.
Please help!
Thanks.

**Comment by CholoTook** [comment]
What does `inxi -F` report plz.

**Comment by HexagonWin** [comment]
Hello. Actually, I switched to another system now, so I'm unable to test right now. :(
Sorry!

**Comment by CholoTook** [comment]
OK, can you close the issue?

**Comment by CholoTook** [comment]
Thanks
