### ISSUE TITLE
Example in Dockerfile

### ISSUE THREAD

**Issue by mikeover** [mdouchement/docker-zoom-us#5]
Can you include an example for how to include this into a Dockerfile for running a zoom client amongst other things? Currently I have: 
```
   FROM mdouchement/zoom-us:latest
   COPY zoomus.conf load/root/.config/zoomus.conf
   RUN /opt/zoom/zoom
```

but building it yields an error `/opt/zoom/zoom: error while loading shared libraries: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory`

**Comment by mdouchement** [comment]
Your host folder `.config` is mounted inside the container with:
https://github.com/mdouchement/docker-zoom-us/blob/c6b15fa5ebba386e3cc101afc6de30fd7f1b8048/scripts/zoom-us-wrapper#L55-L56

Is that not enough for you?
